setuptools: Disable auto discovery
The latest release of setuptools 61.0 made a breaking change[1] and
because of this change `pip install` fails with the following error.

~~~
error: Multiple top-level packages discovered in a flat-layout:
['lib', 'spec', 'manifests', 'releasenotes'].
~~~

Users that don't set ``packages``, ``py_modules``, or `configuration`
are still likely to observe the auto-discovery behavior, which may
halt the build if the project contains multiple directories and/or
multiple Python files directly under the project root.

To disable auto discovery, one can do below in setup.py

~~~
setuptools.setup(..,packages=[],..)
~~~

or

~~~
setuptools.setup(..,py_modules=[],..)
~~~

[1] https://github.com/pypa/setuptools/issues/3197

Note setup.py is not used to install puppet modules. However it is used
to generate a release note, thus should be fixed.

Conflicts:
	setup.py

Signed-off-by: Jiri Podivin <jpodivin@redhat.com>
Change-Id: I6468b31a73339b823f15b70c1e2d5cac450a5ee6
(cherry picked from commit 59a21631281354c9c6c831e903d09e1e6790bb29)
(cherry picked from commit a4481a864c12dc33f8da4c788a5ccf15311708ac)